services:
  - type: web
    name: jlpt-n1-bot
    env: python
    plan: free
    region: oregon
    buildCommand: pip install --prefer-binary -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: RENDER_EXTERNAL_URL
        fromService:
          type: web
          name: jlpt-n1-bot
          property: url
